version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: access_pass_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: access_pass_db
      POSTGRES_USER: analyst
      POSTGRES_PASSWORD: analyst123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./sql/sample_data.sql:/docker-entrypoint-initdb.d/02_sample_data.sql

volumes:
  postgres_data:
